### ISSUE TITLE
FixerIO deprecated API

### ISSUE THREAD

**Issue by aetolus** [amatellanes/fixerio#31]
The fixer.io API endpoint has been deprecated, and API keys are now required for the new one.

I was wondering if you have any plans to update this client? 

https://github.com/fixerAPI/fixer

**Comment by amatellanes** [comment]
Hi @aetolus,

Yes... I'm planning to update to the new endpoint. At least I'd like to update those endpoints you can use with a free API key as soon as possible.

Thanks for your interest!

**Comment by aetolus** [comment]
Thanks @amatellanes, very helpful!

**Comment by fabaff** [comment]
Is there an ETA on those changes? We are using this module in Home Assistant (https://github.com/home-assistant/home-assistant/issues/14911).

**Comment by amatellanes** [comment]
Hi @fabaff,

I'm currently working on that [in this branch](https://github.com/amatellanes/fixerio/tree/feature/update-new-fixerio). I hope to release a new version to support new Fixer endpoint this week... My initial ideal is that this new package version will support [Free Plan](https://fixer.io/product).

**Comment by fabaff** [comment]
Awesome, thanks for the feedback.

Good idea to start with the Free plan. I guess that most people will stick to that. It's sad to see that they only support SSL/TLS for the other plans which will require additional work for all third-party tools.

**Comment by fabaff** [comment]
Just two quick comments for your branch:

- You don't need to test [this](https://github.com/amatellanes/fixerio/blob/feature/update-new-fixerio/fixerio/client.py#L56). The access/api key is not a requirement.
- It would be nice if you could add a timeout to the requests (e.g., [here](https://github.com/amatellanes/fixerio/blob/feature/update-new-fixerio/fixerio/client.py#L109))
-

**Comment by amatellanes** [comment]
Thanks for the comments @fabaff !

My initial idea about [this](https://github.com/amatellanes/fixerio/blob/feature/update-new-fixerio/fixerio/client.py#L56) was using a different API Key from constructor when calling a method... but maybe I'd better remove it for simplicity's sake and perhaps add it in the future.

**Comment by amatellanes** [comment]
Version [1.0.0a0](https://pypi.org/project/fixerio/1.0.0a0/) available.
